### ISSUE TITLE
Getting build error on "npm run build"

### ISSUE THREAD

**Issue by faizanhussainrabbani** [dorsha/login-modal-react-redux#3]
When I try to run "npm run build" I get the following error:

```
> rimraf dist

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

I followed all the steps mentioned in the readme file.

**Comment by dorsha** [comment]
Seems to work for me (after installing bower and running `npm i`):

![image](https://user-images.githubusercontent.com/5429033/53029820-55afa000-3472-11e9-83f0-667975d754d2.png)

Can you try to run the following commands separately and see when you get the failure?
1. `npm run clean`
2. `bower install`
3. `./node_modules/.bin/webpack`

**Comment by faizanhussainrabbani** [comment]
Thanks, it is working when I am typing "npm run build" commands separately.
